### PR TITLE
Option to log to specified file or stdout if `-` is specified

### PR DESCRIPTION
**Pull request by gar1t**

### CODE REVIEW

**Comment by gar1t** [comment]
As with the other two remaining PRs in this submission, the conflict is related to option ordering - I can resolve easily if the change itself is not controversial.

**Comment by yangyanli** [comment]
Looks good to me, could you help resolve the conflict?

**Comment by gar1t** [comment]
Unfortunately this is going to be in conflict again as soon as you merge #114. Same with #111. I think the simplest path is to just merge and resolve in series.

**Comment by gar1t** [comment]
Closing this - will resubmit with combined changes to avoid conflict.

**Pull request closed without merging**
